sudo: required
services:
  - docker

before_install:
  - docker build -t chuanhuiloh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chuanhuiloh/react-test npm test

after_success:
  - docker build -t chuanhuiloh/multi-client ./client
  - docker build -t chuanhuiloh/multi-nginx ./nginx
  - docker build -t chuanhuiloh/multi-server ./server
  - docker build -t chuanhuiloh/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push chuanhuiloh/multi-client
  - docker push chuanhuiloh/multi-nginx
  - docker push chuanhuiloh/multi-server
  - docker push chuanhuiloh/multi-worker